### ISSUE TITLE
If a node with a downstream tree gets disconnected, make sure the downstream tree sticks together longer

### ISSUE THREAD

**Issue by goggledefogger** [common-tater/fireflower#12]
When a node with a downstream tree gets disconnected from its upstream peer, the downstream people don't give it a long enough chance. We should make the downstream peers wait longer to allow for a reconnect, rather than the tree breaking up and having everyone reconnect.

**Comment by jessetane** [comment]
same as #16

**Comment by jessetane** [comment]
by default this library does not cause disconnected branches to break up, though applications can define such a behavior
